# Sample configuration information

# Other configuration files, you can use absolute paths
# or relative to the path to the anylink binary

# Database
db_type = "sqlite3"
db_source = "./conf/anylink.db"
# Certificate file
cert_file = "./conf/vpn_cert.crt"
cert_key = "./conf/vpn_cert.key"
files_path = "./conf/files"
# Log level
log_level = "debug"

# System name
issuer = "XXX company VPN"
# Admin users
admin_user = "admin"
# Admin password: 123456
admin_pass = "$2a$10$UQ7C.EoPifDeJh6d8.31TeSPQU7hM/NOM2nixmBucJpAuXDQNqNke"
# Leave it blank to disable OTP.
# After OTP is enabled, the password is password+6-digit OTP.
# Generate OTP: ./anylink tool -o
admin_otp = ""
# Generate JWT: ./anylink tool -s
jwt_secret = "abcdef.0123456789.abcdef"

# Service listening address
server_addr = ":443"
# Enable DTLS
server_dtls = true
# UDP listening address (any port)
server_dtls_addr = ":443"
# Admin service listening address
admin_addr = ":8800"

# Virtual network type [tun macvtap]
link_mode = "tun"
# IP address pool assigned by the client
ipv4_master = "eth0"
ipv4_cidr = "192.168.90.0/24"
ipv4_gateway = "192.168.90.1"
ipv4_start = "192.168.90.100"
ipv4_end = "192.168.90.200"

# Whether to automatically add NAT
iptables_nat = true

# The client displays detailed error information (be careful when opening the online environment)
display_error = true
