name: Go

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          cd server
          go get -v -t -d ./...

      - name: Build
        run: |
          cd server
          mkdir ui
          touch ui/index.html
          go build -v -o anylink -ldflags "-X main.CommitId=`git rev-parse HEAD`"
          ./anylink tool -v

      - name: Test coverage
        run: |
          cd server
          go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...

      - name: Upload coverage to Codecov
        run: |
          cd server
          bash <(curl -s https://codecov.io/bash)
